[package]
name = "tsk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-flags = "0.3.0"
libc = "0.2.144"


[build-dependencies]
bindgen = "^0.61.0"
